package Controllers;

import java.io.IOException;

import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.stage.Stage;

public class GameSceneController {

	// Event Listener on Button.onAction
	@FXML
	public void btnResetClicked(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void btnGoClicked(ActionEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on Button.onAction
	@FXML
	public void btnMenuClicked(ActionEvent event) throws IOException {
		Parent gameSceneParent = FXMLLoader.load(getClass().getResource("/FXML/MainScene.fxml"));
		Scene gameScene = new Scene(gameSceneParent);
		
		Stage window = (Stage) ((Node)event.getSource()).getScene().getWindow();
		window.setTitle("Sids Wordle");
		window.setScene(gameScene);
		window.show();
	}
}
